name       : pingus
version    : 0.7.6
release    : 3
source     :
    - https://github.com/Pingus/pingus/archive/v0.7.6.tar.gz : c4cd89e1d350d2472f32de5f6266ac9f3658a3620eace3f79efac45db4323b65
license    : GPL-3.0
component  : games.strategy
summary    : Pingus is a Lemmings clone for linux
description: |
    Pingus is a Lemmings clone for linux
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(libevdev)
    - pkgconfig(libpng)
    - pkgconfig(sdl)
    - pkgconfig(SDL_image)
    - pkgconfig(SDL_mixer)
    - libboost-devel
    - libiconv-devel
    - scons
setup      : |
    %patch -p1 < $pkgfiles/missing-header.patch
    sed -i "s|/man1/|/man6/|g" Makefile
build      : |
    scons %JOBS% CCFLAGS="$CFLAGS"
install    : |
    %make_install PREFIX=/usr
    install -D -m00644 $pkgfiles/pingus.desktop $installdir/usr/share/applications/pingus.desktop
